# Replace the text below to customize your site
site_name: Swarna Manjari - MDEF & Fab Lab Barcelona
site_description: Master in Design for Emergent Futures
site_author: Swarna Manjari
copyright: Copyleft 2025 "Swarna Manjari" - GNU Free Documentation License
repo_name: 'Name : mdef25-27'
site_url: https://swarnamanjari-chellapandi.github.io/mdef25-27/
repo_url: 'https://github.com/swarnamanjari-chellapandi/mdef25-27.git'


nav:
  - Home: index.md
  - Who I am: about/me.md
  - let's keep walking :
      - spotting signals:
          - AoWS: term1/02-Atlas of Weak Signals.md

          - publishing: term1/01-publication.md
      
  - designing by doing:
      - ideating: project/ideating.md
      - unpacking: project/unpacking.md
      - fabricating: project/fabricating.md
      - extending: project/extending.md
      - prototyping: project/prototyping.md
      - publishing: term1/01-publication.md
  - currently reading :
      - books: about/books.md
  - I'm thinking about : about/thoughts.md
      




extra:
  social:
    # For other social icons at https://squidfunk.github.io/mkdocs-material/setup/adding-social-links/
  
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/swarna_manjari/
    - icon: fontawesome/brands/github
      link: https://github.com/swarnamanjari-chellapandi

theme:
  features:
    - header.autohide

  name: material

  features:
    - content.tabs
    - content.grid

  
  palette:
    # try other colors https://squidfunk.github.io/mkdocs-material/getting-started/#primary-colors
    primary: yellow
    accent: pink
  font:
    # See available fonts at https://fonts.google.com/
    text: Baskervville
   
  icon:
    logo: material/memory
  favicon: images/favicon.png
  features:
    - instant
    - navigation.expand
    - navigation.indexes
    - navigation.instant
    # - navigation.prune
    # - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking

plugins:
  - search
  - git-revision-date-localized:
      fallback_to_build_date: true

markdown_extensions:
  - extra
  - smarty
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

  - md_in_html
  - admonition
  - codehilite
  - footnotes
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      base_path: 'docs'
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - attr_list
  - pymdownx.tabbed

extra_css:
  - stylesheets/extra.css
  - https://unpkg.com/material-components-web@latest/dist/material-components-web.min.css
